/*UTENTE 1: CLIENTE*/
CREATE USER REGISTRATO IDENTIFIED BY PASSWORD_REGISTRATO;
GRANT CONNECT, CREATE SESSION                      TO REGISTRATO;
GRANT SELECT  ON MULTA                             TO REGISTRATO;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECENSIONE TO REGISTRATO;
GRANT EXECUTE ON EFFETTUA_PRESTITO                 TO REGISTRATO;
GRANT EXECUTE ON EFFETTUA_RESTITUZIONE             TO REGISTRATO;
GRANT EXECUTE ON PRENOTA_POSTO_EVENTO              TO REGISTRATO;
GRANT EXECUTE ON DISDICI_PRENOTAZIONE_POSTO_EVENTO TO REGISTRATO;
GRANT SELECT  ON EVENTI_DISPONIBILI                TO REGISTRATO;
GRANT SELECT  ON LIBRI_CATALOGATI                  TO REGISTRATO;
GRANT SELECT  ON PRESTITI_EFFETTUATI               TO REGISTRATO;
GRANT SELECT  ON RECENSIONI_EFFETTUATE             TO REGISTRATO;

/*UTENTE 2: BIBLIOTECARIO*/
CREATE USER ADDETTO IDENTIFIED BY PASSWORD_ADDETTO;
GRANT CONNECT, CREATE SESSION                     TO ADDETTO;
GRANT SELECT                 ON TURNO             TO ADDETTO;
GRANT SELECT, UPDATE, INSERT ON ASSISTE           TO ADDETTO;
GRANT SELECT, UPDATE         ON REGISTRAZIONE     TO ADDETTO;
GRANT SELECT, UPDATE         ON PRENDE            TO ADDETTO;
GRANT SELECT                 ON SCAFFALE          TO ADDETTO;
GRANT SELECT                 ON MENSOLA           TO ADDETTO;
GRANT SELECT                 ON ORDINE            TO ADDETTO;
GRANT EXECUTE                ON POSIZIONA_COPIE   TO ADDETTO;
GRANT EXECUTE                ON RINNOVA_TESSERA   TO ADDETTO;
GRANT SELECT                 ON COPIE_DISPONIBILI TO ADDETTO;

/*UTENTE 3: DIRETTORE*/
CREATE USER DIRETTORE IDENTIFIED BY PASSWORD_DIRETTORE;
GRANT CONNECT, CREATE SESSION                                TO DIRETTORE;
GRANT SELECT, INSERT, DELETE         ON BIBLIOTECARIO        TO DIRETTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TURNO                TO DIRETTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON EVENTO               TO DIRETTORE;
GRANT INSERT, DELETE                 ON LIBRO                TO DIRETTORE;
GRANT INSERT, DELETE                 ON COPIA                TO DIRETTORE;
GRANT INSERT, DELETE                 ON AUTORE               TO DIRETTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCAFFALE             TO DIRETTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON MENSOLA              TO DIRETTORE;
GRANT SELECT, INSERT                 ON ORDINE               TO DIRETTORE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASA_EDITRICE        TO DIRETTORE;
GRANT EXECUTE                        ON CONTROLLA_INVENTARIO TO DIRETTORE;
GRANT SELECT                         ON COPIE_ORDINATE       TO DIRETTORE;

/*UTENTE 4: ADMIN*/
CREATE USER AMMINISTRATORE IDENTIFIED BY PASSWORD_AMMINISTRATORE;
GRANT CONNECT, CREATE SESSION                      TO AMMINISTRATORE;
GRANT ALL PRIVILEGIES                              TO AMMINISTRATORE;